name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Compile model
        uses: docker://sailavid/ua-modelcompiler
        with:
          entrypoint: /app/PublishModel.sh
          args: /github/workspace/SkillsModel Opc.Ua.Skills /github/workspace/Published
      - name: Upload compiled model
        uses: actions/upload-artifact@v1
        with:
          name: Published
          path: Published
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${GITHUB_WORKSPACE}/Published/*
          git commit -m "[skip ci] Deploy from GitHub Action" -a
      - name: Push compiled model to published branch
        if: steps.extract_branch.outputs.branch == 'master'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}-published
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
